#include <sys/types.h>
#include <sys/ioctl.h>
#include <assert.h>
#include <ctype.h>
#include <hwregs_c.h>
#include <psxapi.h>
#include <psxcd.h>
#include <psxetc.h>
#include <psxgpu.h>
#include <psxgte.h>
#include <psxpad.h>
#include <psxpress.h>
#include <psxsio.h>
#include <psxsn.h>
#include <psxspu.h>
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
